FROM quay.io/centos/centos:stream10

RUN dnf config-manager --set-enabled crb

RUN dnf update -y && \
    dnf install -y \
        wget \
        ca-certificates \
        unzip \
        tar \
        xz \
        which \
        gcc \
        gcc-c++ \
        libstdc++ \
        libstdc++-devel \
        libstdc++-static \
        libatomic \
        protobuf-compiler \
        protobuf-devel \
        rpm \
        cpio \
        java-21-openjdk-devel \
        git \
        rpm-build

RUN wget https://github.com/bazelbuild/bazel/releases/download/8.3.0/bazel-8.3.0-linux-arm64 && \
    chmod +x bazel-8.3.0-linux-arm64 && \
    mv bazel-8.3.0-linux-arm64 /usr/local/bin/bazel && \
    mkdir /app

# Verify installation
RUN bazel --help

WORKDIR /app
CMD ["/bin/bash"]
